#!/bin/bash

CMHOST_CONF=localhost
INSTALL_ERUNNERD_CONF=y
LOG_REMOVE_CONF=No
LSF_HOST_CONF=n
MAX_OPEN_FDS_CONF=
AGENT_NUMBER_CONF=2
REBOOT_CONF=No
SECURE_CONSOLE_CONF=n
SHARED_AGENT_NUMBER_CONF=2
TEMPDIR_CONF=/tmp

CMHOST_CONF=${CMHOST:=$CMHOST_CONF}
CMPORT_CONF=${CMPORT:=$CMPORT_CONF}
INSTALL_ERUNNERD_CONF=${INSTALL_ERUNNERD:=$INSTALL_ERUNNERD_CONF}
LOG_REMOVE_CONF=${LOG_REMOVE:=$LOG_REMOVE_CONF}
LSF_HOST_CONF=${LSF_HOST:=$LSF_HOST_CONF}
MAX_OPEN_FDS_CONF=${MAX_OPEN_FDS:=$MAX_OPEN_FDS_CONF}
AGENT_NUMBER_CONF=${AGENT_NUMBER:=$AGENT_NUMBER_DEFAULT}
REBOOT_CONF=${REBOOT:=$REBOOT_CONF}
SECURE_CONSOLE_CONF=${SECURE_CONSOLE:=$SECURE_CONSOLE_CONF}
SHARED_AGENT_NUMBER_CONF=${SHARED_AGENT_NUMBER_CONF:=$SHARED_AGENT_NUMBER_CONF}
TEMPDIR_CONF=${TEMPDIR:=$TEMPDIR_CONF}


/opt/ecloud/i686_Linux/64/bin/ecconfig \
 -cm $CMHOST_CONF \
 -numagents $AGENT_NUMBER_CONF \
 -lsfhost $LSF_HOST_CONF \
 -secureconsole value \
 -sharedagents $SHARED_AGENT_NUMBER_CONF \
 -tempdir "$TEMPDIR_CONF" \
 -maxopenfds value 
  

if [ -z "$ECA_RESOURCE_NAME" ]; then
    echo "Variable ECA_RESOURCE_NAME is not defined, using host name (${HOSTNAME}) as the name for resource."
    export ECA_RESOURCE_NAME="$HOSTNAME"
fi
echo "Starting ElectricAccelerator Agent '$ECA_RESOURCE_NAME'..."

# Start the second process
echo "<--Log--$0> | Going to run /etc/init.d/erunner"
/etc/init.d/erunner  start
status=$?
echo "<--Log--$0> | Status erunner - $status"
if [ $status -ne 0 ]; then
  echo "<--Log--$0> Failed to start /etc/init.d/erunner: $status"
  exit $status
fi


# Start the third process
echo "<--Log--$0> | Going to run /etc/init.d/ecagent"
/etc/init.d/ecagent  start
status=$?
echo "<--Log--$0> | Status ecagent - $status"
if [ $status -ne 0 ]; then
  echo "<--Log--$0> Failed to start /etc/init.d/ecagent: $status"
fi
tail -f /opt/ecloud/i686_Linux/APL.txt
