#!/bin/bash

if ! [ -d /etc/sysconfig  ]; then 
    mkdir /etc/sysconfig
fi
if ! [ -e /opt/ecloud/i686_Linux/conf/ecagent.conf ] ; then
    cp /opt/ecloud/i686_Linux/conf/ecagent.conf /etc/sysconfig/ecagent.conf
    chmod 0644 /etc/sysconfig/ecagent.conf
fi
chmod +x /opt/ecloud/rules/ecagent
chmod +x /opt/ecloud/rules/erunner

