#!/bin/bash


if [ -z "$ECA_RESOURCE_NAME" ]; then
    echo "Variable ECA_RESOURCE_NAME is not defined, using host name (${HOSTNAME}) as the name for resource."
    export ECA_RESOURCE_NAME="$HOSTNAME"
fi
echo "Starting ElectricAccelerator CM '$ECA_RESOURCE_NAME'..."
(tail -n 4 -f /opt/ecloud/i686_Linux/logs/accelerator.log) &
echo "<--Log--$0> | /opt/ecloud/i686_Linux/64/bin/clustermanager"
(/opt/ecloud/i686_Linux/64/bin/clustermanager  start ) &
(tail -n 4 -f /var/log/cmlog) &
bash

