#!/bin/bash
#copy file to init.d
EC_ProductVersion=$BUILD_VERSION
#services
cp /opt/ecloud/i686_Linux/64/bin/clustermanager  /etc/init.d/clustermanager

/bin/chmod 755 /etc/init.d/clustermanager
/bin/chown root  /etc/init.d/clustermanager


/usr/sbin/useradd -d /opt/ecloud -c "" "eacmuser"
/bin/chown -R "eacmuser" "/opt/ecloud/i686_Linux"

/bin/chmod 755 /opt/ecloud/i686_Linux/jre/bin
/bin/chmod 755 /opt/ecloud/i686_Linux/apache/bin
/bin/chmod 755 /opt/ecloud/i686_Linux/apache/tmp
/bin/chmod 755 /opt/ecloud/i686_Linux/64/bin
/bin/chmod 755 /opt/ecloud/i686_Linux/unsupported


#create links
#ln -s /etc/init.d/ecagent /etc/rc0.d/K20ecagent
#ln -s /etc/init.d/ecagent /etc/rc2.d/S77ecagent
#ln -s /etc/init.d/ecagent /etc/rc3.d/S77ecagent
#ln -s /etc/init.d/ecagent /etc/rc5.d/S77ecagent
#ln -s /etc/init.d/ecagent /etc/rc6.d/K20ecagent
#-----------erunner-----------
#copy file to init.d
#cp /opt/ecloud/i686_Linux/64/bin/erunner /etc/init.d/erunner
#change permissions
#/bin/chmod 755 /etc/init.d/erunner
#/bin/chown root  /etc/init.d/erunner
#create links
#ln -s /etc/init.d/erunner /etc/rc0.d/K20erunner
#ln -s /etc/init.d/erunner /etc/rc2.d/S77erunner
#ln -s /etc/init.d/erunner /etc/rc3.d/S77erunner

